### PR TITLE
Fix to test setup

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).

### :arrow_heading_up: Summary

Fix hatch test:test which was not working locally

### :closed_umbrella: Related issues

n/a

### :microscope: Tests

n/a

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
I can't reproduce this.

I wonder if something was wrong with your virtual env as `pytest` should be installed in your `PATH`.

**Comment by JimMadge** [comment]
@craddm Can you reproduce this?

**Comment by jemrobinson** [comment]
I can only reproduce this in one environment and I'm not sure how it got into the state it's in. However, I think `python -m pytest` is never **wrong** and should be guaranteed to give you the right `pytest` anyway.

**Comment by craddm** [comment]
Similarly, I can't reproduce this locally, but happy with what should be a more robust way of running it.

**Comment by JimMadge** [comment]
Feels odd to introduce a fix for a broken virtual env. It is almost a feature to point out that something is wrong.

I'm not sure if it is most robust. If `pytest` fails your `$PATH` is likely wrong, if `python -m pytest` fails your `PYTHON_PATH` is likely wrong 🤔.

**Comment by jemrobinson** [comment]
Closing as unnecessary.

**Pull request closed without merging**
