### PR TITLE
Fixes for AzureSdk blob handling

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

- Ensure the `blob_client()` method is used everywhere we need a `BlobServiceClient`
- Ensure that exceptions raised by `blob_client()` are caught and (if appropriate) reraised by the calling function
- Make error messages more informative about what went wrong

### :closed_umbrella: Related issues

n/a

### :microscope: Tests

Tested on an existing SRE

### CODE REVIEW

**Review by craddm — COMMENTED** [review]
In #2129 I need to use a blob client, but can't use this function as it requires a blob name. Is it possible to make it an optional parameter?

**Comment by jemrobinson** [comment]
I think that would be fine. If you're happy with these changes otherwise, maybe the easiest solution is to merge this as-is, merge release-v5.0.0 into your branch for #2129 and then make the blob name optional there. What do you think?

**Comment by jemrobinson** [comment]
Or actually, separate this function into a `blob_service_client` and `blob_client` function. I can do that here if you'd prefer?

**Comment by jemrobinson** [comment]
@craddm : Does f14ae787e fix your issue?

**Comment by craddm** [comment]
> @craddm : Does https://github.com/alan-turing-institute/data-safe-haven/commit/f14ae787e75ed81aa4218ef857899b2c18f4d67c fix your issue?

Tested this with some edits to #2129 and it works!

**Comment by jemrobinson** [comment]
Great - are we OK to merge this one then?

**Comment by craddm** [comment]
LGTM

**Pull request merged**
