### PR TITLE
Add timeout for guac postgres queries

### LINKED ISSUE #1607: Pulumi: Issues with guacamole login
After a period of inactivity, Guacamole no longer offers a login page. Instead, you simply receive an error message:

guac-error

On inspecting the container logs, a standout error was this:

```
[http-nio-8080-exec-9] WARN o.a.i.d.pooled.PooledDataSource - Execution of ping query 'SELECT 1' failed: An I/O error occurred while sending to the backend.
```

This error led me to an issue on the Guacamole site, [https://issues.apache.org/jira/browse/GUACAMOLE-919], which suggests the problem is due to the connection between guacamole and the PostGRES database backing it. 

Manually changing the suggested environment variable on the running container seems to fix the issue - will give it a little longer to see if it recurs.

### PR DESCRIPTION
**Pull request by craddm**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [ ] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [ ] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

Adds a timeout for PostGRES sockets when Guacamole tries to connect to the database

### :closed_umbrella: Related issues

Closes #1607

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
LGTM, are we still testing this change?

**Comment by jemrobinson** [comment]
Testing is ongoing. @craddm to confirm if/when we're happy.

**Comment by craddm** [comment]
So far so good. Since the issue seems to relate to periods of inactivity, I'd say if everything is still fine tomorrow morning, this has done the trick.

**Comment by craddm** [comment]
No further issues today, so seems like this worked.

**Pull request merged**
