### PR TITLE
Remove egress steps not carried out by System Manager

### LINKED ISSUE #1420: Move egress download doc section from System Manager doc somewhere else
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Unclear in [this egress doc](https://alan-turing-institute.github.io/data-safe-haven/develop/roles/system_manager/manage_data.html#data-egress) that the download part with Azure Storage Explorer should ideally be completed by the egress contact (find the correct terminology for this person in the docs).

## :memo: Required documentation changes

- [ ] Move the parts from "Open Azure Storage Explorer ([download](https://azure.microsoft.com/en-us/products/storage/storage-explorer/) it if you don’t have it)" onwards to another doc
- [ ] Link to this doc in [Turing's own docs](https://alan-turing-institute.github.io/trusted-research/tasks/data_egress/index.html)

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the **develop branch**.
- [x] Your branch is up-to-date with the **develop branch** (you probably started your branch from `develop` but it may have changed since then).
- [ ] If-and-only-if your changes are not yet ready to merge, you have marked this pull request as a **draft** pull request and added '[WIP]' to the title.
- [ ] If-and-only-if you have changed any Powershell code, you have run the code formatter. You can do this with `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>`.

### :arrow_heading_up: Summary

The second part of this section is instructions for the egress-ee, not the System Manager - I'm removing this to avoid confusion. I will also update Turing internal documentation to have the information that is removed here, making egress documented in the same way as ingress.

### :closed_umbrella: Related issues

Closes #1420

Tandem PR on Turing docs: https://github.com/alan-turing-institute/trusted-research/pull/156

### :microscope: Tests

```
cd docs
make html
```

### CODE REVIEW

**Comment by JimMadge** [comment]
Hi @edwardchalstrey1,

I think this section of documentation is a bit poor and confusing in general.

- It isn't clear who receives the outputs. It mentions both 'you' (_i.e._ the system manager) and the data provider.
- It doesn't make clear that there should be a review process before creating the egress link!

I have made some changes and pushed them to [this branch](https://github.com/alan-turing-institute/data-safe-haven/tree/egress-doc-edits). Could you add those to your fork's branch and push them so they are part of the PR or [allow edits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by edwardchalstrey1** [comment]
Screenshot 2023-03-29 at 13 53 29
@JimMadge it looks like you should already be able to edit this PR?

**Comment by edwardchalstrey1** [comment]
@JimMadge I was able to sync your edits

**Comment by JimMadge** [comment]
> Screenshot 2023-03-29 at 13 53 29 @JimMadge it looks like you should already be able to edit this PR?

Hmm, yes it works. Not sure what I was doing wrong before 🤦

**Comment by JimMadge** [comment]
I'm not worried about the remaining link checking errors. The website exists and the check is probably failing due to rate limiting.

@edwardchalstrey1 and @harisood can you build and read the documentation for a sanity check? I think it is quite poor in the current state (see my comment above).

**Comment by edwardchalstrey1** [comment]
@JimMadge 
> * It isn't clear who receives the outputs. It mentions both 'you' (_i.e._ the system manager) and the data provider.

Updated

> * It doesn't make clear that there should be a review process before creating the egress link!

Do we want to say this in the DSH docs? I'm thinking that we document our own processes for the Turing prod DSH for this, but for the open source software is it not up to whoever uses it to figure this out?

**Comment by JimMadge** [comment]
Thanks @edwardchalstrey1 I missed that reference.

> > * It doesn't make clear that there should be a review process before creating the egress link!
> 
> Do we want to say this in the DSH docs? I'm thinking that we document our own processes for the Turing prod DSH for this, but for the open source software is it not up to whoever uses it to figure this out?

I'm pretty certain that we do. It isn't a discussion of the Turing's (or any organisations) particular process. It is just stating that outputs need to be reviewed. I don't think you can have a functional TRE if you can remove data without review.

This is also consistent with how the data ingress steps are described.

**Comment by edwardchalstrey1** [comment]
> > Do we want to say this in the DSH docs? I'm thinking that we document our own processes for the Turing prod DSH for this, but for the open source software is it not up to whoever uses it to figure this out?
> I'm pretty certain that we do. It isn't a discussion of the Turing's (or any organisations) particular process. It is just stating that outputs need to be reviewed. I don't think you can have a functional TRE if you can remove data without review.

Agreed, just realised you have added this already

@JimMadge I'm happy with this now, but let me know if you think further edits needed

**Review by craddm — APPROVED** [review]
LGTM

**Pull request merged**
