### PR TITLE
Move log analytics to SRE

### LINKED ISSUE #1905: Move log analytics to SRE
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We do not need a central log analytics workspace so this could be moved to the SRE

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

- Move log analytics workspace to SRE
- Move Azure private DNS zones to SRE
- Remove unused SHM monitoring component

### :closed_umbrella: Related issues

Closes #1905 

### :microscope: Tests

Tested on a fresh SHM/SRE deployment

### CODE REVIEW

**Comment by craddm** [comment]
From a test deployment, this is mostly working except for the final step - ingesting logs from the DCR to the log workspace using Diagnostic Settings - So the logs aren't currently being ingested.

**Comment by jemrobinson** [comment]
What I found yesterday was that you don't need the diagnostic setting, but you do need to wait for a while (docs suggest 20 minutes).

**Comment by craddm** [comment]
Ok, will check back later. 40 mins so far and not connected.

**Comment by jemrobinson** [comment]
@craddm : I agree, it's still not connected. I've captured this in #1931 as I think it's beyond the scope of this PR. Are you happy with it otherwise?

**Review by craddm — APPROVED** [review]
Yes, LGTM

**Pull request merged**
