### PR TITLE
Allow 'Internet' for data providers IP

### PR DESCRIPTION
**Pull request by JimMadge**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

#2246 

### :arrow_heading_up: Summary

Allows data providers (as well as research users) IP addresses to be defined as the Azure service tag 'Internet'.

### :microscope: Tests

Tested on a new deployment. Ingress and Egress blobs anonymous access and with SAS token. Checked download from egress is possible with appropriate SAS token. Checked upload to ingress is possible with appropriate SAS token.

With the storage account set to allow all network connections and blob public access disabled (which is default, but also explicitly set here),

With the storage account URL, you cannot anonymously access the containers

Screenshot 2024-10-31 at 15 35 07

With a valid SAS token you can access the containers and manipulate the data according to the permissions the SAS allows

Screenshot 2024-10-31 at 15 36 09

### CODE REVIEW

**Comment by JimMadge** [comment]
This might be a bit more tricky as storage accounts use [IP address ranges](https://learn.microsoft.com/en-gb/azure/storage/common/storage-network-security?tabs=azure-portal#grant-access-from-an-internet-ip-range) and not service tags for restricting external access.

It is possible to allow connection from any network.

**Review by craddm — APPROVED** [review]
LGTM

**Review by jemrobinson — CHANGES_REQUESTED** [review]
Should this be targeting `develop` instead of `latest`?

**Comment by JimMadge** [comment]
> Should this be targeting `develop` instead of `latest`?

I did have it as a hotfix. However, happy to move it to the next minor release as that should be soon, and this does change networking somewhat.

**Review by jemrobinson — APPROVED** [review]

**Pull request merged**
