### PR TITLE
Release v5.0.0

### LINKED ISSUE #2104: Release: v5.0.0
## :white_check_mark: Checklist

Refer to the [Deployment](https://data-safe-haven.readthedocs.io/en/latest/deployment) section of our documentation when completing these steps.

- [x] Consult the `data-safe-haven/VERSIONING.md` guide and determine the version number of the new release. Record it in the title of this issue.
- [x] Create a release branch called e.g. `release-v0.0.1`
- [x] Draft a changelog for the release similar to our previous releases, see https://github.com/alan-turing-institute/data-safe-haven/releases

### For patch releases only

- [ ] Confirm that the resource to which the patch applies can be successfully deployed

### For minor releases and above

- [x] Deploy an SHM from this branch and save a transcript of the deployment logs
- Using the new image, deploy a tier 2 and a tier 3 SRE
    - [x] Save the transcript of your tier 2 SRE deployment
    - [x] Save the transcript of your tier 3 SRE deployment
- [x] Complete the [Security evaluation checklist](https://data-safe-haven.readthedocs.io/en/latest/deployment/security_checklist.html) from the deployment documentation
- [x] Add the new versions tag as an active build on [Read The Docs](https://readthedocs.org) (You can add as a hidden build, before release, to preview)

### For major releases only

- [x] Confirm that a third party has carried out a full penetration test evaluating:
  1. external attack surface
  1. ability to exfiltrate data from the system
  1. ability to transfer data between SREs
  1. ability to escalate privileges on the SRD.

### Update documentation

- [x] Update supported versions in SECURITY.md
- [x] Update pen test results in VERSIONING.md

## :computer: Release information

- **Version number:** 5.0.0
- **SHM ID:** turtle
- **T2 SRE ID:** donatello
- **T3 SRE ID:** leonardo

## :deciduous_tree: Deployment problems

Probable time out of resource creation in one SRE.
Repeat deployment attempts failed because the resource was created, but the outputs were not present in the Pulumi stack state.
Deleting the resources in the portal and redeploying fixed the issue, as after a refresh Pulumi recreated the resources are collected the outputs.
No fix necessary.

Smoke tests are failing on the `Tier 3`, which is configured with `pre-approved` software packages allowed.
See #2107 

Fatal error in Ansible (see #2099) can stop following tasks from running.
It was necessary to run desired state again (or wait for the timer to trigger) for the workspaces to be properly configured.

### PR DESCRIPTION
**Pull request by JimMadge**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :closed_umbrella: Related issues

Closes #2104

### CODE REVIEW

**Comment by JimMadge** [comment]
Deployment from [d00e55c](https://github.com/alan-turing-institute/data-safe-haven/pull/2106/commits/d00e55c27f4211743c1090688b97dff6a76590d5) works without error.

**Comment by jemrobinson** [comment]
@JimMadge : Can you work through the security checklist and update it if necessary (e.g. we may not need to check SRE to SRE connectivity)?

**Comment by JimMadge** [comment]
Can connect to the workspace. Everything seems to be working fine there.

**Comment by jemrobinson** [comment]
Tore down SRE baron from 93d57dc

**Review by craddm — APPROVED** [review]
LGTM

**Pull request merged**
