### PR TITLE
Document removal of persistent SRE storage accounts

### LINKED ISSUE #1362: Write data deletion script and improve docs
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Update the teardown process to include removing the persistent data container from Azure, so data gets deleted when SRE is deleted.

## :steam_locomotive: How could this be done?

- [ ] Write a powershell script that destroys the storage account in the SHM this and test it on a non-production SRE
- [x] #1366
- ~~Include the new script as a final step in `SRE_Teardown.ps1`~~ see discussion below
- [ ] Update [the docs](https://alan-turing-institute.github.io/data-safe-haven/v4.0.1/roles/system_manager/manage_deployments.html#remove-a-complete-safe-haven)

### PR DESCRIPTION
**Pull request by craddm**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [ ] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [x] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

Adds instructions for deleting persistent SRE storage from the SHM, while explaining why this is a manual rather than automatic process.

### :closed_umbrella: Related issues

Closes #1362 

### :microscope: Tests

Documentation only

### CODE REVIEW

**Comment by JimMadge** [comment]
@helendduncan would you or a TRESA team member like to review this?

**Comment by helen-d-little** [comment]
This PR updates documentation regarding deployment of storage accounts (current link [here](https://data-safe-haven.readthedocs.io/en/latest/deployment/deploy_sre_microsoft_rds.html#deploy-storage-accounts)) to more accurately reflect where and how storage accounts for SREs are built and named. 

This PR also updates the documentation (current link [here](https://data-safe-haven.readthedocs.io/en/latest/roles/system_manager/manage_deployments.html#tear-down-any-attached-sres)) around the teardown of SREs to explicitly state that the data stored in the host safe haven’s persistent data is not removed, and that if/when this data is to be removed it is to be done via the Azure portal.

Does that sound correct @craddm?

**Comment by craddm** [comment]
> This PR updates documentation regarding deployment of storage accounts (current link [here](https://data-safe-haven.readthedocs.io/en/latest/deployment/deploy_sre_microsoft_rds.html#deploy-storage-accounts)) to more accurately reflect where and how storage accounts for SREs are built and named.
> 
> This PR also updates the documentation (current link [here](https://data-safe-haven.readthedocs.io/en/latest/roles/system_manager/manage_deployments.html#tear-down-any-attached-sres)) around the teardown of SREs to explicitly state that the data stored in the host safe haven’s persistent data is not removed, and that if/when this data is to be removed it is to be done via the Azure portal.
> 
> Does that sound correct @craddm?

Yep, exactly - does it change the docs clearly enough or did I miss something?

**Comment by helen-d-little** [comment]
> > This PR updates documentation regarding deployment of storage accounts (current link [here](https://data-safe-haven.readthedocs.io/en/latest/deployment/deploy_sre_microsoft_rds.html#deploy-storage-accounts)) to more accurately reflect where and how storage accounts for SREs are built and named.
> > This PR also updates the documentation (current link [here](https://data-safe-haven.readthedocs.io/en/latest/roles/system_manager/manage_deployments.html#tear-down-any-attached-sres)) around the teardown of SREs to explicitly state that the data stored in the host safe haven’s persistent data is not removed, and that if/when this data is to be removed it is to be done via the Azure portal.
> > Does that sound correct @craddm?
> 
> Yep, exactly - does it change the docs clearly enough or did I miss something?

I think it is perfectly clear :)

**Review by helen-d-little — APPROVED** [review]
Update of documentation is clear and concise

**Review by JimMadge — APPROVED** [review]

**Pull request merged**
