### PR TITLE
Use a single resource group for all SRE resources

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

Use a single Azure resource group for all SRE resources

### :closed_umbrella: Related issues

n/a

### :microscope: Tests

Tested on a new SRE deployment

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
Is there an advantage to this?

I'm not sure if it is better for findability to have one RG per SRE or many RGs for different types of resource. @craddm what do you think?

**Comment by craddm** [comment]
> Is there an advantage to this?
> 
> I'm not sure if it is better for findability to have one RG per SRE or many RGs for different types of resource. @craddm what do you think?

I was just wondering exactly the same thing - I feel like things will get buried.

**Comment by jemrobinson** [comment]
It's a good question. I mildly prefer one resource group for the whole SRE just because some of our existing resource groups either only have a single resource in them (e.g. apt proxy server and backup) or refer to resources in other groups. There's currently not a clean separation between what lives in each resource group (apart from the fact that they're deployed from a single Component) and it's actually a bit annoying to keep switching RGs when trying to debug something.

However, this isn't something I feel very strongly about, so happy to drop it if you both prefer.

**Comment by JimMadge** [comment]
Might ask to hang back on merging until #1892 is merged to avoid the conflicts.

**Comment by jemrobinson** [comment]
Thoughts @JimMadge @craddm ?

- arguments for:
  - fewer resources to deploy (and correspondingly less code)
  - easier to find things in the portal
  - no confusion about which resources live in which RG
- arguments against:
  - lots of resources in a single RG

**Comment by craddm** [comment]
> Thoughts @JimMadge @craddm ?
> 
> * arguments for:
>   
>   * fewer resources to deploy (and correspondingly less code)
>   * easier to find things in the portal
>   * no confusion about which resources live in which RG
> * arguments against:
>   
>   * lots of resources in a single RG

I think the "lots of resources in a single RG" point slightly contradicts the "easier to find things in the portal" point, but I have to admit I sometimes am unsure which resources live in which RG, just like you say. 

I'm actually sort of coming round to the single RG viewpoint, having just gone back to the portal and realized you can sort by type etc

**Comment by jemrobinson** [comment]
Watching how other people use the portal, I think it's quite rare to have the "RGs are folders" mindset. Mostly people search by name or type (or occasionally by tag).

**Review by craddm — APPROVED** [review]
Now we've got a few SREs up at once, i'm just running a test deployment with this, and I think I'm converted. As said above, can easily group by type or other fields, or even (shock horror) just filter

**Pull request merged**
