### PR TITLE
Use SHM name instead of description for Entra app

### LINKED ISSUE #2242: Entra application uses description rather than name of SHM
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** debian Bookworm
- **Data Safe Haven version:** develop

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

When deploying the SHM, an Entra application is created. The name of that application uses the `description` field of the context, rather than the `name`. This means if somebody (e.g. somebody other than the original creator) tries to redeploy the SHM but doesn't match the description precisely, it creates a new application. Subsequently deploying an SRE fails (with a long and horrifying Python `event loop is closed` error) which seems to be because there's a mismatch between the expected client secret and the credentials of the new application (see below). 

The application could be avoided by using the name of the SHM/context. Otherwise entra apps might proliferate if different admins describe contexts differently.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

In this image, two of the applications - `gitea testing` and `stuff` are from the same SHM, but with different descriptions in the context.

image

```none
    azuread:index:Group sre_entra_group_privileged_user_group_name  error: 1 error occurred:
    azuread:index:Group sre_entra_group_privileged_user_group_name **failed** 1 error
Diagnostics:
  azuread:index:Group (sre_entra_group_privileged_user_group_name):
    error: 1 error occurred:
        * building client: unable to obtain access token: clientCredentialsToken: received HTTP status 401 with response:
{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client
secret value, not the client secret ID, for a secret added to app '2b4bed0c-1c4d-4b3a-b18a-078a8ac337a5'. Trace ID: e72597b3-e195-4d06-8432-ecba191e3100
Correlation ID: 48dad7cd-a0e2-4b74-971f-08d060d312c1 Timestamp: 2024-10-18 10:52:07Z","error_codes":[7000215],"timestamp":"2024-10-18
10:52:07Z","trace_id":"e72597b3-e195-4d06-8432-ecba191e3100","correlation_id":"48dad7cd-a0e2-4b74-971f-08d060d312c1","error_uri":"https://login.microsofto
nline.com/error?code=7000215"}
```

</details>

## :recycle: To reproduce

Deploy an SHM, then update the context with a new `description`, redeploy it, and try to deploy an SRE.

### PR DESCRIPTION
**Pull request by craddm**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :arrow_heading_up: Summary

Uses the SHM/context name as part of the name of the Entra application, instead of the description. 

This ensures the application will have a consistent name.

### :closed_umbrella: Related issues

Closes #2242

### :microscope: Tests

Tested locally

### CODE REVIEW

**Review by jemrobinson — APPROVED** [review]
LGTM. Nice catch.

**Comment by jemrobinson** [comment]
N.B. Should this target 5.0.1-rc1 instead of develop? Sounds like a bugfix we will want in the patch release.

**Comment by craddm** [comment]
> N.B. Should this target 5.0.1-rc1 instead of develop? Sounds like a bugfix we will want in the patch release.

Could do; but depends if we're merging develop into 5.0.1-rc1, as this is up-to-date with develop rather than based on 5.0.1-rc1

**Comment by jemrobinson** [comment]
@craddm : Sorry, for this to work you should probably grab that single commit and apply it on top of `release-v5.0.1rc1`.

**Review by JimMadge — CHANGES_REQUESTED** [review]
Could you check for other places where the description is used?

It isn't ideal that it lives in the context but I think we should ensure changing it doesn't produce any destructive operations.

**Comment by craddm** [comment]
> Could you check for other places where the description is used?
> 
> It isn't ideal that it lives in the context but I think we should ensure changing it doesn't produce any destructive operations.

I haven't spotted anywhere else - every other use I've found is just for information (e.g. printing messages to console)

**Review by JimMadge — APPROVED** [review]

**Pull request merged**
