### PR TITLE
Show invalid config

### LINKED ISSUE #2006: Adding new items to the config file
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

If new items are ever added to the config file, it is not possible to update an existing config with them, since the first step in doing so is to download and validate the existing config, which will always fail.

## :steam_locomotive: How could this be done?

Either default values could be added when downloading an existing config or the validation step could be skipped.

### PR DESCRIPTION
**Pull request by JimMadge**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :closed_umbrella: Related issues

Closes #2006 

### :microscope: Tests

Tested locally after editing configurations in Azure storage.

### CODE REVIEW

**Review by jemrobinson — CHANGES_REQUESTED** [review]
This looks sensible but it doesn't fix the biggest issue: we need a way to overwrite an existing config (which might not parse correctly) in the `upload()` method. Currently, this fails when trying to obtain a diff.

**Comment by JimMadge** [comment]
> This looks sensible but it doesn't fix the biggest issue: we need a way to overwrite an existing config (which might not parse correctly) in the `upload()` method. Currently, this fails when trying to obtain a diff.

Ah, good point!

I think we can leave the other commands though. I think most of the time the program terminating when it encounter an invalid configuration is a feature.

**Comment by JimMadge** [comment]
I've added a `--force` option to upload,

```console
❯ hatch run dsh config upload ./sre-oda.yaml
You are logged into the Azure CLI as:
        user: Jim Madge (…)
        tenant: turing.ac.uk (…)
Are these details correct? [y/n] (y): y
Found 2 validation errors when trying to load SREConfig.
dockerhub.username: {'access_token': '…'} - Field required
name: {'azure': {'location': 'uksouth', 'subscription_id':
'…', 'tenant_id': '…'},
'description': 'Oda', 'dockerhub': {'access_token': '…'},
'sre': {'admin_email_address': '…', 'admin_ip_addresses':
['…'], 'data_provider_ip_addresses': ['…'], 'databases': [],
'remote_desktop': {'allow_copy': False, 'allow_paste': False}, 'research_user_ip_addresses':
['…'], 'software_packages': 'pre-approved', 'storage_quota_gb': {'home': 100,
'shared': 100}, 'timezone': 'Europe/London', 'workspace_skus': ['Standard_D8s_v5']}} - Field
required
SREConfig configuration is invalid.
'sre-oda.yaml' does not contain a valid SREConfig configuration.
Remote configuration for SRE 'oda' is not valid. Dumping remote file.
azure:
  location: uksouth
  subscription_id: …
  tenant_id: …
description: Oda
dockerhub:
  access_token: …
sre:
  admin_email_address: …
  admin_ip_addresses:
  - …
  data_provider_ip_addresses:
  - …
  databases: []
  remote_desktop:
    allow_copy: false
    allow_paste: false
  research_user_ip_addresses:
  - …
  software_packages: pre-approved
  storage_quota_gb:
    home: 100
    shared: 100
  timezone: Europe/London
  workspace_skus:
  - Standard_D8s_v5

To overwrite the remote config, use `dsh config upload --force`
❯ hatch run dsh config upload --force ./sre-oda.yaml
You are logged into the Azure CLI as:
        user: Jim Madge (…)
        tenant: turing.ac.uk (…)
Are these details correct? [y/n] (y): y
❯ hatch run dsh config show oda
You are logged into the Azure CLI as:
        user: Jim Madge (…)
        tenant: turing.ac.uk (…)
Are these details correct? [y/n] (y): y
azure:
  location: uksouth
  subscription_id: …
  tenant_id: …
description: Oda
dockerhub:
  access_token: …
  username: …
name: oda
sre:
  admin_email_address: …
  admin_ip_addresses:
  - …
  data_provider_ip_addresses:
  - …
  databases: []
  remote_desktop:
    allow_copy: false
    allow_paste: false
  research_user_ip_addresses:
  - …
  software_packages: pre-approved
  storage_quota_gb:
    home: 100
    shared: 100
  timezone: Europe/London
  workspace_skus:
  - Standard_D8s_v5

```

**Review by craddm — APPROVED** [review]
LGTM

**Pull request merged**
