### PR TITLE
[WIP] Prevent teardown of SHM if any SREs are deployed within it

### PR DESCRIPTION
**Pull request by craddm**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :arrow_heading_up: Summary

Checks for deployed SREs within an SHM and prevents `dsh shm teardown` if any are found.

image

### :closed_umbrella: Related issues

Related to #2252 

### :microscope: Tests

Tested locally

### CODE REVIEW

**Comment by JimMadge** [comment]
Hmm, I think this got closed when the target branch was deleted.

Sorry @craddm 🙇! Are you able to change the target to develop?

**Comment by craddm** [comment]
Won't let me - it's fine, I'll do a new one for develop

**Comment by JimMadge** [comment]
That's a pain, you still have your branch locally though?

**Comment by craddm** [comment]
Yep!

**Comment by jemrobinson** [comment]
The GitHub interface is infuriating sometimes!

**Pull request closed without merging**
