### PR TITLE
Move update servers to SRE

### LINKED ISSUE #1832: Move update proxy to Docker
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

The Ubuntu repository proxy currently runs on a VM. This should be updated to run in a Docker image.

## :steam_locomotive: How could this be done?

- Write a minimal Docker image repository
- Replace the VM with an Azure Container Image that uses this repository

### LINKED ISSUE #1837: Move update servers from SHM to SRE
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We should move the update servers out of the SHM and into the SRE

## :steam_locomotive: How could this be done?

Deploy a new Dockerised squid-deb-proxy container in the SRE.

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).

### :arrow_heading_up: Summary

- Add Dockerised apt proxy server to the SRE
- Remove update server VM from SHM
- Remove unused networking and components from SHM

Note that the workspaces **must** be deployed after the apt-proxy is fully configured. To achieve this we make the workspace dependent on the apt-proxy private DNS hostname, which itself is dependent on the apt-proxy private IP address which is not available until the container reaches "Running" status.

### :closed_umbrella: Related issues

Closes #1837. Closes #1832.

### :microscope: Tests

Tested on fresh SHM and SRE deployment

### CODE REVIEW

**Comment by JimMadge** [comment]
Would it be sensible to merge #1820 into this?

**Comment by jemrobinson** [comment]
I *think* they're independent. Is #1820 ready to merge?

**Comment by JimMadge** [comment]
I think there will be some conflicts (hopefully easy to fix 🤞). `config.tags` and `config.context` don't exist any more, for example.

**Comment by JimMadge** [comment]
> Is https://github.com/alan-turing-institute/data-safe-haven/pull/1820 ready to merge?

It definitely breaks the code. So we could either finish the fixes in #1839 first, or merge it and continue #1839. What do you think?

**Comment by jemrobinson** [comment]
- This PR (#1847) is ready to merge as-is
- #1820 would break develop if merged as-is
- #1839 fixes some of those problems but hasn't been tested

I suggest we do the following:

- Merge #1847 once it's been reviewed
- Merge #1839 into #1820 whenever you feel like it's ready (before or after testing)
- We co-work on testing #1820 once you think it's in a working state
- I'm happy to fix merge issues on #1820 that are caused by merging #1847.

**Review by craddm — APPROVED** [review]
LGTM

**Pull request merged**
