### PR TITLE
Fix Pulumi/dsh Python mismatch

### LINKED ISSUE #2239: Pulumi using wrong Python/Python path in pipx install
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:** 

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

After pipx install, when calling `dsh` Pulumi will look for a Python interpreter and find system Python, not the Python venv with all of the dependencies. It will fail because of missing packages.

On option to fix,
[can declare venv path](https://www.pulumi.com/docs/iac/languages-sdks/python/#pypi-packages) in Pulumi package settings.
We set these [here](https://github.com/alan-turing-institute/data-safe-haven/blob/53058974451dc0febb535d594e4849b74067f4b2/data_safe_haven/infrastructure/project_manager.py#L86)

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

Set PULUMI_PYTHON_CMD to use the same Python executable that is being used by dsh. 

Thanks for the pointer @craddm !

### :closed_umbrella: Related issues

Closes #2239 

### :microscope: Tests

Tested locally, but we should test on the rc1 branch once this is merged into it

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
I'm not sure this will fix #2239 on its own. I don't think it is just the Python interpreter but also the `PYTHONPATH`.

**Comment by craddm** [comment]
Seems to work on my Docker container

**Comment by jemrobinson** [comment]
Yeah, it also worked for me. I'm not sure why, but I assume it sets the path correctly behind the scenes?

**Comment by JimMadge** [comment]
Interesting, maybe the interpreter "knows" where it's modules are, or the default path is relative to the executable file or something. If this works on its own though I don't see much benefit in also finding and setting the venv path :+1:.

**Review by JimMadge — APPROVED** [review]

**Comment by jemrobinson** [comment]
I tried the venv method and couldn't get it to work, so if this fix works for @helendduncan then I'm happy with it :)

**Comment by JimMadge** [comment]
> Seems to work on my Docker container

Reading this a second time, does that mean this works in an environment where it _didn't_ work before (a `pipx` install), or it still works in your container where it worked previously?

**Comment by craddm** [comment]
> > Seems to work on my Docker container
> 
> Reading this a second time, does that mean this works in an environment where it _didn't_ work before (a `pipx` install), or it still works in your container where it worked previously?

`pipx` didn't work previously - same issue with not finding the modules. Note this is standalone Docker container, not the `.devcontainer` that I usually use.

**Comment by JimMadge** [comment]
Great, that sounds like a positive result for this change working then :tada:.

**Comment by jemrobinson** [comment]
Confirmed working by @helendduncan

**Pull request merged**
