### PR TITLE
Use pip-compile for package resolution

### LINKED ISSUE #1493: SRD build issue: Python installation fails
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS Ventura 13.4
- **Data Safe Haven version:** 4.0.4

## :cactus: Powershell module versions

```
./CheckRequirements.ps1                                                       2023-06-26 16:05:32 [WARNING]: Powershell version: 7.3.4
2023-06-26 16:05:32 [WARNING]: The currently supported version of Powershell is 7.3.2.
2023-06-26 16:05:32 [WARNING]: In case of errors originating from Powershell code, ensure that you are running the currently supported version.
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.MonitoringSolutions module version: 0.1.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.Accounts module version: 2.11.1
2023-06-26 16:05:32 [SUCCESS]: [✔] Microsoft.Graph.Identity.DirectoryManagement module version: 1.21.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.DataProtection module version: 0.4.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Powershell-Yaml module version: 0.4.2
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.RecoveryServices module version: 5.4.1
2023-06-26 16:05:32 [SUCCESS]: [✔] Microsoft.Graph.Applications module version: 1.21.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.Resources module version: 6.5.1
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.Storage module version: 4.7.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Microsoft.Graph.Authentication module version: 1.21.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.PrivateDns module version: 1.0.3
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.Monitor module version: 4.2.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Microsoft.Graph.Users module version: 1.21.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.Network module version: 5.3.0
2023-06-26 16:05:32 [SUCCESS]: [✔] Az.KeyVault module version: 4.9.1
2023-06-26 16:05:33 [SUCCESS]: [✔] Poshstache module version: 0.1.10
2023-06-26 16:05:33 [SUCCESS]: [✔] Az.Automation module version: 1.9.0
2023-06-26 16:05:33 [SUCCESS]: [✔] Az.Dns module version: 1.1.2
2023-06-26 16:05:33 [SUCCESS]: [✔] Az.Compute module version: 5.3.0
2023-06-26 16:05:33 [SUCCESS]: [✔] Az.OperationalInsights module version: 3.1.0
```

## :no_entry_sign: Describe the problem

When building an SRE from the `release-v4.0.4` branch, the smoke tests fail on all Python versions - inspecting the SRD build log reveals there was a problem with installing Python (see logs below).

## :deciduous_tree: Log messages

<details>
<summary>
Failed Python 3.10 installation on candidate VM:
</summary>

```
• Installing xgboost (1.7.6)

  ImportError

  cannot import name 'Python2Supports' from 'virtualenv.create.describe' (/opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/virtualenv/create/describe.py)

  at /opt/pyenv/versions/3.10.12/lib/python3.10/site-packages/virtualenv/create/via_global_ref/builtin/python2/python2.py:6 in <module>
        2│ import json
        3│ import os
        4│ from pathlib import Path
        5│
    →   6│ from virtualenv.create.describe import Python2Supports
        7│ from virtualenv.create.via_global_ref.builtin.ref import PathRefToDest
        8│ from virtualenv.info import IS_ZIPAPP
        9│ from virtualenv.util.zipapp import read as read_from_zipapp
       10│

  • Installing xlrd (2.0.1)
Could not install Python 3.10.12!
Cloud-init v. 23.1.2-0ubuntu0~20.04.2 running 'modules:final' at Mon, 26 Jun 2023 15:43:16 +0000. Up 74.00 seconds.
2023-06-26 16:41:23,896 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-06-26 16:41:23,897 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
System setup through cloud-init is finished. Configuration took 3563.61 seconds
```
</details>
<details>
<summary>Python safety check failure during SRD build</summary>

```none
Code          : ProvisioningState/succeeded
Level         : Info
DisplayStatus : Provisioning succeeded
Message       : Enable succeeded: 
                [stdout]
                [2023-06-23 08:47:56: SUCCESS] Build started: 
                [2023-06-23 08:48:54: SUCCESS] Running cloud-init modules: 57s
                [2023-06-23 09:17:00: SUCCESS] Installing/updating Ubuntu packages: 28m5s
                [2023-06-23 09:17:33: SUCCESS] Preparing system for installation: 32s
                [2023-06-23 09:19:51: SUCCESS] Installing additional deb/source packages: 2m18s
                [2023-06-23 09:24:33: SUCCESS] Updating ClamAV database: 4m42s
                [2023-06-23 09:25:05: SUCCESS] Installing Spark/Hadoop: 32s
                [2023-06-23 09:36:18: SUCCESS] Installing Julia and packages: 11m13s
                [2023-06-23 09:44:07: SUCCESS] Installing Python (3.9.17) and packages: 7m49s
                [2023-06-23 09:48:33: FAIL   ] Installing Python (3.10.12) and packages: 4m26s
                [2023-06-23 09:48:34: FAIL   ] Finished build: 1h0m37s
                [2023-06-23 09:48:33: INFO   ] Memory available: 17 GB
                [2023-06-23 09:48:33: INFO   ] ..... mean usage:  10.39% =>  1.7 GB
                [2023-06-23 09:48:33: INFO   ] ...... min usage:   5.38% =>  0.9 GB
                [2023-06-23 09:48:33: INFO   ] ...... max usage:  28.45% =>  4.8 GB
                [2023-06-23 09:48:33: INFO   ] CPU available: 8 cores
                [2023-06-23 09:48:33: INFO   ] ..... mean usage:  26.19% =>  2.1 cores
                [2023-06-23 09:48:33: INFO   ] ...... min usage:   0.10% =>  0.0 cores
                [2023-06-23 09:48:33: INFO   ] ...... max usage: 100.00% =>  8.0 cores
                [2023-06-23 09:48:33: WARNING] Safety check found problems with Python 3.9.17
                [2023-06-23 09:48:33: WARNING] ... transformers [4.19.2] is affected by issue 51450 (for versions ['<4.23.0'])
```

</details>

<details>
<summary>Failed smoke tests on SRE</summary>

```none
bats run_all_tests.bats 
run_all_tests.bats
 ✓ Julia packages
 ✓ Julia functionality
 ✗ Python packages (3.9)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_packages' in file run_all_tests.bats, line 28,
    in test file run_all_tests.bats, line 67)
     `test_python_packages '3.9'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✗ Python functionality (3.9)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_functionality' in file run_all_tests.bats, line 21,
    in test file run_all_tests.bats, line 70)
     `test_python_functionality '3.9'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✓ Python virtual environments (3.9)
 ✗ Python package repository (3.9)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_repository' in file run_all_tests.bats, line 35,
    in test file run_all_tests.bats, line 76)
     `test_python_repository '3.9'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✗ Python packages (3.10)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_packages' in file run_all_tests.bats, line 28,
    in test file run_all_tests.bats, line 81)
     `test_python_packages '3.10'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✗ Python functionality (3.10)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_functionality' in file run_all_tests.bats, line 21,
    in test file run_all_tests.bats, line 85)
     `test_python_functionality '3.10'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✓ Python virtual environments (3.10)
 ✗ Python package repository (3.10)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_repository' in file run_all_tests.bats, line 35,
    in test file run_all_tests.bats, line 91)
     `test_python_repository '3.10'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✗ Python packages (3.11)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_packages' in file run_all_tests.bats, line 28,
    in test file run_all_tests.bats, line 96)
     `test_python_packages '3.11'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✗ Python functionality (3.11)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_functionality' in file run_all_tests.bats, line 21,
    in test file run_all_tests.bats, line 99)
     `test_python_functionality '3.11'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✓ Python virtual environments (3.11)
 ✗ Python package repository (3.11)
   (from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_repository' in file run_all_tests.bats, line 35,
    in test file run_all_tests.bats, line 105)
     `test_python_repository '3.11'' failed with status 127
   /opt/tests/run_all_tests.bats: line 14: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 10: pyenv: command not found
   /opt/tests/run_all_tests.bats: line 15: pyenv: command not found
 ✗ R packages
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 178,
    in test file run_all_tests.bats, line 114)
     `assert_output --regexp 'All [0-9]+ packages are installed'' failed
   
   -- regular expression does not match output --
   regexp (1 lines):
     All [0-9]+ packages are installed
   output (2 lines):
     Error in library(stringr) : there is no package called ‘stringr’
     Execution halted
   --
   
 ✓ R functionality
 ✓ R package repository
 ✓ Mounted drives (/data)
 ✓ Mounted drives (/home)
 ✓ Mounted drives (/output)
 ✓ Mounted drives (/shared)
 ✓ Mounted drives (/scratch)

22 tests, 10 failures

```

</details>

## :recycle: To reproduce

- Build SRD image from 4.0.4 release branch
- Deploy SRE using this image

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [x] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

- Replace `poetry` with `pip-compile` for Python package resolution
- This should avoid the issues in #1493 which required several packages to be dropped
- NB. I *think* the PyTorch version on PyPI *is* compatible with machines that don't have CUDA so this shouldn't be a problem. Can anyone verify?

### :closed_umbrella: Related issues

Closes #1493

### :microscope: Tests

Tested locally, but could do with independent testing.

### CODE REVIEW

**Comment by jemrobinson** [comment]
@edwardchalstrey1: Can you try a build from this branch and see whether everything works for you? By replacing poetry with pip-compile we should avoid the `Python2Supports` errors. I haven't removed `torch` here because I *think* it should work.

**Review by JimMadge — APPROVED** [review]
LGTM.

I think the long term solution is to remove these altogether. It is a pain to support and we have a better way of installing Python packages for _most_ Tiers.

It might be more idiomatic if the unpinned requirements are in a file called `requirements.in` and the output of `pip-compile` is called `requirements.txt`. However, that is not a hill to die on.

**Comment by jemrobinson** [comment]
> It might be more idiomatic if the unpinned requirements are in a file called `requirements.in` and the output of `pip-compile` is called `requirements.txt`. However, that is not a hill to die on.

Agreed - I just wanted to make the most minimal change in this PR.

**Comment by edwardchalstrey1** [comment]
Deploying a new candidate VM from this branch now. Will let you know the results

**Comment by edwardchalstrey1** [comment]
Success:

```
[2023-08-01 09:22:42: SUCCESS] Build started:
[2023-08-01 09:24:12: SUCCESS] Running cloud-init modules: 1m29s
[2023-08-01 09:53:57: SUCCESS] Installing/updating Ubuntu packages: 29m45s
[2023-08-01 09:54:34: SUCCESS] Preparing system for installation: 36s
[2023-08-01 09:56:59: SUCCESS] Installing additional deb/source packages: 2m25s
[2023-08-01 09:59:34: SUCCESS] Updating ClamAV database: 2m35s
[2023-08-01 10:22:46: SUCCESS] Installing Spark/Hadoop: 23m12s
[2023-08-01 10:35:19: SUCCESS] Installing Julia and packages: 12m33s
[2023-08-01 10:51:27: SUCCESS] Installing Python (3.9.17) and packages: 16m8s
[2023-08-01 11:06:04: SUCCESS] Installing Python (3.10.12) and packages: 14m37s
[2023-08-01 11:19:17: SUCCESS] Installing Python (3.11.4) and packages: 13m13s
[2023-08-01 11:19:29: SUCCESS] Configuring pyenv: 12s
[2023-08-01 11:49:50: SUCCESS] Installing R packages: 30m21s
[2023-08-01 11:50:08: SUCCESS] Cleaning up the build environment: 18s
[2023-08-01 11:50:15: SUCCESS] Checking environment configuration: 7s
[2023-08-01 11:50:16: SUCCESS] Finished build: 2h27m34s
[2023-08-01 11:50:15: INFO   ] Memory available: 17 GB
[2023-08-01 11:50:15: INFO   ] ..... mean usage:  11.12% =>  1.9 GB
[2023-08-01 11:50:15: INFO   ] ...... min usage:   5.35% =>  0.9 GB
[2023-08-01 11:50:15: INFO   ] ...... max usage:  54.65% =>  9.2 GB
[2023-08-01 11:50:15: INFO   ] CPU available: 8 cores
[2023-08-01 11:50:15: INFO   ] ..... mean usage:  30.74% =>  2.5 cores
[2023-08-01 11:50:15: INFO   ] ...... min usage:   0.10% =>  0.0 cores
[2023-08-01 11:50:15: INFO   ] ...... max usage: 100.00% =>  8.0 cores
```

**Pull request merged**
