### PR TITLE
Pulumi: pin all docker image versions

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [x] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

Pin all docker images to MAJOR.MINOR.PATCH and set to latest version at time of writing

### :closed_umbrella: Related issues

n/a

### :microscope: Tests

Not tested

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
What do we think about the balance between update burden and confidence when pinning to patch versions?

Related to https://github.com/alan-turing-institute/data-safe-haven/pull/1501

**Comment by jemrobinson** [comment]
Probably pinning to major versions is the right idea, but I guess they don't exist for all these images. How about writing a CI job that checks version numbers?

**Comment by JimMadge** [comment]
I think pinning to major whenever possible is a good approach.

I was hoping depdendabot would be able to check for updates in docker-compose-like files but I don't think it does.

**Comment by jemrobinson** [comment]
I'm going to close this but maybe revisit if we can think of a sensible way to automate it.

**Pull request closed without merging**
