### PR TITLE
Merge development updates into 5.0.1rc1 release branch

### PR DESCRIPTION
**Pull request by JimMadge**
## :white_check_mark: Checklist

- [ ] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [ ] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [ ] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### CODE REVIEW

**Comment by JimMadge** [comment]
I would guess it is the psycopg downgrade that is causing a conflict here.

**Comment by jemrobinson** [comment]
Are you sure this is a good idea? We need to make sure that rc1 is tested and produces a deployment that actually works. The current branch I think meets these requirements.

**Comment by JimMadge** [comment]
> Are you sure this is a good idea? We need to make sure that rc1 is tested and produces a deployment that actually works. The current branch I think meets these requirements.

Probably 😅. I don't think it is really a rc, it is a pointer to where a team are currently testing. The milestone isn't finished yet and work towards that is still going on on `develop`.

**Comment by craddm** [comment]
I agree with Jim; this rc1 felt more like laying down a marker for where we were at when TRESA were starting testing rather than a genuine release candidate

**Comment by JimMadge** [comment]
Closing due to merge conflicts on develop, I'll do the merge on a new branch and open a PR from that.

**Pull request closed without merging**
