### PR TITLE
Switch to psycopg[binary]

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

- Switch our dependency from `psycopg` to `psycopg[binary]`

From [the installation page](https://www.psycopg.org/psycopg3/docs/basic/install.html) `psycopg[binary]` packages its own version of `libpq`. This avoids a requirement that the end user has `libpq` installed.

Note that this would mean that we drop support for platforms that aren't supported by `psycopg[binary]` which include Apple Mac M1.

### :closed_umbrella: Related issues

Attempting to run `dsh` commands using `psycopg` without `libpq` installed gives errors like the following:

```
Traceback (most recent call last):
  File "/Users/jrobinson/.local/bin/dsh", line 5, in <module>
    from data_safe_haven.commands.cli import main
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/commands/__init__.py", line 1, in <module>
    from .cli import application
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/commands/cli.py", line 10, in <module>
    from .config import config_command_group
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/commands/config.py", line 9, in <module>
    from data_safe_haven.config import ContextManager, DSHPulumiConfig, SHMConfig, SREConfig
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/config/__init__.py", line 1, in <module>
    from .context import Context
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/config/context.py", line 12, in <module>
    from data_safe_haven.external import AzureSdk
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/external/__init__.py", line 5, in <module>
    from .interface.azure_postgresql_database import AzurePostgreSQLDatabase
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/data_safe_haven/external/interface/azure_postgresql_database.py", line 7, in <module>
    import psycopg
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 118, in <module>
    import_from_libpq()
  File "/Users/jrobinson/.local/pipx/venvs/data-safe-haven/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 110, in import_from_libpq
    raise ImportError(
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```

### :microscope: Tests

Tested locally

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
> Note that this would mean that we drop support for platforms that aren't supported by psycopg[binary] which include Apple Mac M1.

Is that true? The docs say ARM MacOS < 14.0 is not supported.

I vaguely recall that installing psycopg with the bundled libraries wasn't recommended as it wasn't a full implementation. Not sure if I'm thinking about a different package or if that has changed. The docs suggest it is a full libpq.

If it installed without error on a good range of modern systems I think that is better than asking users to install libpq/psql.

**Comment by craddm** [comment]
Was going to add that this does actually improve things in Windows 10 at least, as I had to install `psycopg[binary]` (hadn't had chance to report yet) to be able to run dsh commands.

**Comment by jemrobinson** [comment]
@craddm : Are you happy to merge this then?

**Review by craddm — APPROVED** [review]

**Comment by craddm** [comment]
Fine by me (works fine for my setup)

**Comment by jemrobinson** [comment]
Merged (works on my machine) :rofl:

**Pull request merged**
