### PR TITLE
Add basic config commands

### PR DESCRIPTION
**Pull request by JimMadge**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [x] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

Adds a minimal set of config commands to allow the program to work with the new Config class in #1658.

### CODE REVIEW

**Comment by craddm** [comment]
Ran out of time to do a full review right now, but got as far as creating the template. Tried to upload an incorrectly completed one and failed, sensibly.

**Comment by craddm** [comment]
Ok, so as of now these functions do what they are supposed to do - they allow creation/modification/upload of a config file. Couple of notes:

1. There's no validation of the `fqdn`.
2. I can't deploy an SHM after running creating the context and the config. This may not matter for this PR, though.

**Comment by JimMadge** [comment]
I'll look at the fqdn validation (I think there was a function for that).

I wouldn't be surprised if it breaks deployment, certainly with the current deployment commands. I want to change that as well though. I think it would make most sense to address that in a different PR, although it does mean we will break the head of the branch. What do you think @craddm?

**Comment by craddm** [comment]
I agree, probably best in another PR. No problem with that at this stage. Here's the specific error:

```
2024-01-15 10:54:13 [   ERROR]  stderr: error: error listing stacks: could not list bucket: blob (code=NotFound): GET                              cli.py:98
https://shmfishescontext.blob.core.windows.net/pulumi                                                                                                       
2024-01-15 10:54:13 [   ERROR] --------------------------------------------------------------------------------                                    cli.py:98
2024-01-15 10:54:13 [   ERROR] RESPONSE 404: 404 The specified container does not exist. 
```

**Comment by JimMadge** [comment]
@craddm I've added validation for FQDNs.

**Review by craddm — APPROVED** [review]
LGTM

**Pull request merged**
