### PR TITLE
File structuring

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [x] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).

### :arrow_heading_up: Summary

An idea of a possible file/inheritance restructuring.

### :closed_umbrella: Related issues

n/a

### :microscope: Tests

Local tests passing

### CODE REVIEW

**Review by JimMadge — COMMENTED** [review]
I like this structure,

- I like keeping context configuration and DSH configuration separate. They do feel like quite different things to me.
- We _could_ pass the information `AzureSeialisableModel.upload` needs instead of a `Context` instance to remove that import.
- Having the serialisers in their own package feels right.
- I still wonder if breaking the types down more would be useful. `data_safe_haven.enums.ANIMAL` might be clearer than `data_safe_haven.types.ANIMAL`.
- `utility` is a lot neater now. I don't mind having that or a `helpers` package.
- Breaking up the `functions` package might be good. In particular we could have
  ```python
   from data_safe_haven import validators

   validators.timezone(a)
   ```
   instead of 
   ```python
   from data_safe_haven import functions

   functions.validate_timezone(a)
   ```

**Comment by JimMadge** [comment]
Also, I think we have some sensible nesting now. Like in the `infrastructure` package, where the top level `__init__.py` only exports what you need at a high level, the stack managers. The finer details are in sub-packages which are only needed in `infrastructure` anyway :+1:.

**Comment by JimMadge** [comment]
This may also be an opportunity to rename `StackManager` to `ProjectManager` or similar.

**Comment by JimMadge** [comment]
I'm going to try making some of those changes.

**Comment by jemrobinson** [comment]
I would also like to move the AzureSDK deployment stuff (currently in `context > context_infra` into `infrastructure`) if you're comfortable with that.

**Comment by JimMadge** [comment]
> I would also like to move the AzureSDK deployment stuff (currently in `context > context_infra` into `infrastructure`) if you're comfortable with that.

I think we should be consistent. `config` and `infrastructure` are separate so `context` and `context_infra` should be too.

I think maybe a `context_infrastructure` package/module might be better as `infrastructure` is currently all Pulumi stuff. (I think it used to be called `pulumi`?)

**Comment by jemrobinson** [comment]
I can see the argument behind keeping AzureSDK and Pulumi deployment stuff separate, but perhaps this could look like:

```
data_safe_haven/infrastructure
├── __init__.py
├── sdk
│   ├── __init__.py
│   ├── some
│   ├── files/folders
│   └── here
└── pulumi
    ├── __init__.py
    ├── some
    ├── files/folders
    └── here
```

with

```
data_safe_haven/infrastructure/__init__.py

from .pulumi import SHMStackManager ...
from .sdk import ContextInfra ...

...
```

so you could do something like

```
from data_safe_haven.infrastructure import ContextInfra

context_infra = ContextInfra(context)
context_infra.create()
```

```
from data_safe_haven.infrastructure import SHMStackManager

stack = SHMStackManager(context, config, pulumi_project)
stack.deploy()
```

and we could possibly unify the names/function names at the same time.

**Comment by JimMadge** [comment]
I think I will stop here.

Changing `AzureSerialisableConfig.upload` or breaking down `types` doesn't seem worth it right now.

I think it would be good to restructure the `commands` package, at least to be consistent with how it is laid out. But perhaps that can be part of #1836?

**Comment by jemrobinson** [comment]
Yes, let's do `commands` separately. I feel like I prefer `dsh shm <verb>` over `dsh <verb> shm` but happy to be convinced otherwise.

**Comment by JimMadge** [comment]
Yes, I prefer <object> <verb> too :100:.

**Review by JimMadge — APPROVED** [review]

**Pull request merged**
