### PR TITLE
Move security group creation to Pulumi

### LINKED ISSUE #2158: Create Entra security groups with Pulumi
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Create Entra security groups with Pulumi instead of SREProvisioningManager.

## :steam_locomotive: How could this be done?

Use the `pulumi-azuread` Provider.

### PR DESCRIPTION
**Pull request by jemrobinson**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).

### :vertical_traffic_light: Depends on

n/a

### :arrow_heading_up: Summary

- Create a Pulumi application during SHM deployment with permissions to edit groups
- Use this application (and service principal) to initialise the `pulumi-azuread` provider
  - create Entra groups

**N.B.** This adds a dependency on `pulumi-azuread` and (more importantly) creates an extra Entra application during SHM deployment which has permissions to read and write Entra groups.

### :closed_umbrella: Related issues

Closes #2158

### :microscope: Tests

Tested on a new SRE deployment

### CODE REVIEW

**Review by arvydas-nauckunas-tg — APPROVED** [review]

**Review by JimMadge — COMMENTED** [review]
Looks good.

It would be nice to have coverage for the new lines in the Context class and SRE commands.

Is the plan to extend the use of `pulumi-azuread`? It looks like it would let us manage other Entra things in a declarative way. Groups, Users, Applications and so on.

**Comment by jemrobinson** [comment]
> It would be nice to have coverage for the new lines in the Context class and SRE commands.

I'll take a look.

> Is the plan to extend the use of `pulumi-azuread`? It looks like it would let us manage other Entra things in a declarative way. Groups, Users, Applications and so on.

Yes, but I'll work on this in a separate PR (I've already separated this into different issues).

**Comment by jemrobinson** [comment]
@JimMadge : I've added some tests. Is there anything obvious missing?

**Review by JimMadge — APPROVED** [review]
LGTM :+1:

**Pull request merged**
