### PR TITLE
Release v4.1.0

### LINKED ISSUE #1544: Release: 4.1.0
## :white_check_mark: Checklist

Refer to the [Deployment](https://data-safe-haven.readthedocs.io/en/latest/deployment) section of our documentation when completing these steps.

- [x] Consult the `data-safe-haven/VERSIONING.md` guide and determine the version number of the new release. Record it in the title of this issue.
- [x] Create a release branch called e.g. `release-v0.0.1`
- [x] Draft a changelog for the release similar to our previous releases, see https://github.com/alan-turing-institute/data-safe-haven/releases
- [x] Deploy an SHM from this branch and save a transcript of the deployment logs
- [ ] Build an SRE compute image (SRD) and save transcripts of the logs
- Using the new image, deploy two SREs which between them cover tiers 2 and 3 and Guacamole/Microsoft RDS
    - [ ] Save the transcript of your tier 2 SRE deployment
    - [ ] Save the transcript of your tier 3 SRE deployment
- [ ] Complete the [Security evaluation checklist](https://data-safe-haven.readthedocs.io/en/latest/deployment/security_checklist.html) from the deployment documentation

## :computer: Release information

- **Version number:** 4.1.0
- **SHM ID:** orange (https://github.com/alan-turing-institute/trusted-research/issues/216)
- **T2 SRE ID:** lemon (https://github.com/alan-turing-institute/trusted-research/issues/235)
- **T3 SRE ID:** grape (https://github.com/alan-turing-institute/trusted-research/issues/236)
- **T2 MSRDS SRE ID:** kiwi (https://github.com/alan-turing-institute/trusted-research/issues/240)

## :deciduous_tree: Deployment problems

See https://github.com/alan-turing-institute/data-safe-haven-team/issues/21

Additional PRs: https://github.com/alan-turing-institute/data-safe-haven/pulls?q=is%3Apr+is%3Aclosed+base%3Arelease-v4.1.0+base%3Arelease-v4.0.4

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
## :white_check_mark: Checklist

- [x] You have given your pull request a meaningful title (_e.g._ `Enable foobar integration` rather than `515 foobar`).
- [x] You are targeting the appropriate branch. If you're not certain which one this is, it should be **`develop`**.
- [x] Your branch is up-to-date with the **target branch** (it probably was when you started, but it may have changed since then).
- [ ] You have marked this pull request as a **draft** and added `'[WIP]'` to the title if needed (if you're not yet ready to merge).
- [ ] You have formatted your code using appropriate automated tools (for example `./tests/AutoFormat_Powershell.ps1 -TargetPath <path to file or directory>` for Powershell).

### :arrow_heading_up: Summary

All changes from the 4.1.0 release

### :closed_umbrella: Related issues

Closes #1544 

### :microscope: Tests

See #1544

### CODE REVIEW

**Review by JimMadge — CHANGES_REQUESTED** [review]
Hold until we have checked the deployment logs and security checklist.

**Comment by jemrobinson** [comment]
@craddm : are you using this branch on @edwardchalstrey1's repo or the `release-v4.1.0` branch on this repo? If the latter, I think we should close this PR and open a new one from the branch you're using.

**Comment by craddm** [comment]
Yes, I'm using the branch from the main repo (which was up-to-date with Ed's) so best close this and I'll do a new one.

**Comment by jemrobinson** [comment]
Superceded by new PR

**Pull request closed without merging**
